/// A catalogue language the API accepts.
class Language {
  const Language(this.code, this.name);

  final String code;
  final String name;
}

/// Every language the API accepts, sorted by name; codes mirror the backend's languages.ts, which rejects anything else.
const List<Language> languages = [
  Language('AFR', 'Afrikaans'),
  Language('AMH', 'Amharic'),
  Language('ARA', 'Arabic'),
  Language('BEN', 'Bengali'),
  Language('BUL', 'Bulgarian'),
  Language('CMN', 'Chinese (Simplified)'),
  Language('CMN_TRAD', 'Chinese (Traditional)'),
  Language('HRV', 'Croatian'),
  Language('CZE', 'Czech'),
  Language('DAN', 'Danish'),
  Language('NLD', 'Dutch'),
  Language('ENG', 'English'),
  Language('EST', 'Estonian'),
  Language('PES', 'Farsi'),
  Language('FIL', 'Filipino (Tagalog)'),
  Language('FIN', 'Finnish'),
  Language('FRA', 'French'),
  Language('DEU', 'German'),
  Language('ELL', 'Greek'),
  Language('HAU', 'Hausa'),
  Language('HEB', 'Hebrew'),
  Language('HIN', 'Hindi'),
  Language('HUN', 'Hungarian'),
  Language('IND', 'Indonesian'),
  Language('ITA', 'Italian'),
  Language('JPN', 'Japanese'),
  Language('KOR', 'Korean'),
  Language('LAV', 'Latvian'),
  Language('LIT', 'Lithuanian'),
  Language('MSA', 'Malay'),
  Language('MAR', 'Marathi'),
  Language('NOR', 'Norwegian'),
  Language('POL', 'Polish'),
  Language('PT_BR', 'Portuguese (Brazilian)'),
  Language('RON', 'Romanian'),
  Language('RUS', 'Russian'),
  Language('SRB', 'Serbian'),
  Language('SLK', 'Slovak'),
  Language('SPA', 'Spanish'),
  Language('SWA', 'Swahili'),
  Language('SWE', 'Swedish'),
  Language('TAM', 'Tamil'),
  Language('TEL', 'Telugu'),
  Language('THA', 'Thai'),
  Language('TUR', 'Turkish'),
  Language('UKR', 'Ukrainian'),
  Language('URD', 'Urdu'),
  Language('VIE', 'Vietnamese'),
  Language('YOR', 'Yoruba'),
  Language('ZUL', 'Zulu'),
];

/// Country whose flag stands for a language; both ISO 639-2 B and T spellings, as the API sends either.
const Map<String, String> _flagCountry = {
  'ENG': 'GB',
  'SPA': 'ES',
  'FRA': 'FR',
  'FRE': 'FR',
  'DEU': 'DE',
  'GER': 'DE',
  'ITA': 'IT',
  'POR': 'PT',
  'PT_BR': 'BR',
  'NLD': 'NL',
  'DUT': 'NL',
  'POL': 'PL',
  'ARA': 'SA',
  'HIN': 'IN',
  'URD': 'PK',
  'BEN': 'BD',
  'CMN': 'CN',
  'ZHO': 'CN',
  'CHI': 'CN',
  'CMN_TRAD': 'TW',
  'JPN': 'JP',
  'KOR': 'KR',
  'TUR': 'TR',
  'RUS': 'RU',
  'SWE': 'SE',
  'NOR': 'NO',
  'DAN': 'DK',
  'FIN': 'FI',
  'ISL': 'IS',
  'VIE': 'VN',
  'THA': 'TH',
  'IND': 'ID',
  'MSA': 'MY',
  'MAY': 'MY',
  'FIL': 'PH',
  'TGL': 'PH',
  'ELL': 'GR',
  'GRE': 'GR',
  'CES': 'CZ',
  'CZE': 'CZ',
  'SLK': 'SK',
  'SLO': 'SK',
  'HUN': 'HU',
  'RON': 'RO',
  'RUM': 'RO',
  'BUL': 'BG',
  'HRV': 'HR',
  'SRP': 'RS',
  'SRB': 'RS',
  'UKR': 'UA',
  'HEB': 'IL',
  'FAS': 'IR',
  'PES': 'IR',
  'PER': 'IR',
  'TAM': 'IN',
  'TEL': 'IN',
  'MAR': 'IN',
  'GUJ': 'IN',
  'PAN': 'IN',
  'KAN': 'IN',
  'MAL': 'IN',
  'NEP': 'NP',
  'SIN': 'LK',
  'KHM': 'KH',
  'LAO': 'LA',
  'MYA': 'MM',
  'BUR': 'MM',
  'MON': 'MN',
  'KAZ': 'KZ',
  'UZB': 'UZ',
  'AZE': 'AZ',
  'HYE': 'AM',
  'ARM': 'AM',
  'KAT': 'GE',
  'GEO': 'GE',
  'SQI': 'AL',
  'ALB': 'AL',
  'MKD': 'MK',
  'SLV': 'SI',
  'BOS': 'BA',
  'EST': 'EE',
  'LAV': 'LV',
  'LIT': 'LT',
  'SWA': 'KE',
  'AFR': 'ZA',
  'ZUL': 'ZA',
  'YOR': 'NG',
  'HAU': 'NG',
  'AMH': 'ET',
};

/// Name for a stored language code, the code itself if unknown, or [fallback] when unset.
String languageLabel(String? code, [String fallback = '']) {
  if (code == null || code.trim().isEmpty) return fallback;
  final upper = code.trim().toUpperCase();
  for (final language in languages) {
    if (language.code == upper) return language.name;
  }
  return code;
}

/// Flag asset for a language code, or null where none is mapped.
String? flagAssetFor(String? code) {
  final country = code == null ? null : _flagCountry[code.trim().toUpperCase()];
  return country == null ? null : 'assets/flags/$country.svg';
}
